# Generated by Django 5.2.6 on 2025-09-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='creaeted_time',
            new_name='created_time',
        ),
    ]
